In [1]:
import numpy as np
from pychunkedgraph.graph import ChunkedGraph, ChunkedGraphMeta
from pychunkedgraph.graph.meta import ChunkedGraphMeta, GraphConfig, DataSource

ds = DataSource(
  EDGES= "gs://chunkedgraph/minnie65_0/edges",
  COMPONENTS= "gs://chunkedgraph/minnie65_0/components",
  WATERSHED= "gs://microns-seunglab/minnie65/ws_minnie65_0"
)
gc = GraphConfig(
  CHUNK_SIZE= [256, 256, 512]
)
cg = ChunkedGraph(graph_id="akhilesh-minnie65-1")

/usr/local/lib/python3.7/site-packages/python_jsonschema_objects/__init__.py:53: UserWarning: Schema version http://json-schema.org/draft-04/schema not recognized. Some keywords and features may not be supported.
  self.schema["$schema"]


In [2]:
edges = cg.read_chunk_edges([cg.get_chunk_id(layer=2,x=50,y=100,z=0)])
edges = edges["between"].get_pairs()
nodes = np.unique(edges)
parents = cg.get_roots(nodes)
d = dict(zip(parents, nodes))
print(d)

{864691138338302132: 75582971913961693, 864691137629078617: 75512534450307707, 864691137995403800: 75582903194484819, 864691137995404568: 75582834475009044, 864691138741942725: 75582971913961542, 864691137995404824: 75582903194484963, 864691136334203586: 75582971913961503}


In [3]:
# edges = np.array([[94803535283198313, 94803466563722624]],dtype=np.uint64)
# between
edges = np.array([[94524946524577880, 94595315268752176]],dtype=np.uint64)

print(cg.get_cross_chunk_edges_layer(edges))
print(cg.get_roots(edges[0]))

[8]
[864691139327226349 864691139527061485]


In [4]:
# parents = np.uint64(edges[0][0])
# while parents and parents.size:
#     parents = cg.get_parent(parents)
#     print(parents)

In [5]:
from pychunkedgraph.graph.edits import add_edges
from pychunkedgraph.graph.utils.context_managers import TimeIt

edges = np.array(edges, dtype=np.uint64)
with TimeIt("add_edge"):
    print(add_edges(cg, atomic_edges=edges))

Start add_edge
   Start get_parents edges
   4.1484832763671875e-05

2 2 [166512171818156502]
2 2 [166512171818156502]

2 2 [166652840587035216 166723278050689566]
2 2 [166652840587035216 166723278050689566]
Cannot find root id 238589352450457642, 7, 2020-02-13 04:12:57.933000+00:00

3 3 [238870827427170695]
3 3 [238870827427170695]

4 4 [311107923180792595]
4 4 [311107923180792595]

5 5 [383522884267609136]
5 5 [383522884267609136]
Cannot find root id 455162629527175203, 7, 2020-02-13 04:13:02.569000+00:00
Cannot find root id 525232306542084131, 12, 2020-02-13 04:13:04.891000+00:00

7 7 [527554475100710789]
7 7 [527554475100710789]

8 8 [525232306542084131 595601050720271701]
8 8 [595601050719748112 595601050720271701]
Cannot find root id 668784544664518691, 12, 2020-02-13 04:13:10.682000+00:00
   [864691128455135360, 864691128455135361]
15.873968839645386


In [9]:
cg.get_children(864691128455135360)

array([595601050719748112], dtype=uint64)

In [16]:
cg.get_children(864691128455135361)

array([668784544664518691], dtype=uint64)

In [13]:
cg.get_parent(668784544668828344)

864691139527061485

In [12]:
cg.get_parents(np.array([595601050719748112, 668784544664518691], dtype=np.uint64))
cg.get_parents(np.array([595601050719748112, 595601050720271701], dtype=np.uint64))

array([864691128455135360, 668784544668828344], dtype=uint64)