In [1]:
import numpy as np
from pychunkedgraph.graph import ChunkedGraph, ChunkedGraphMeta
from pychunkedgraph.graph.meta import ChunkedGraphMeta, GraphConfig, DataSource

ds = DataSource(
  EDGES= "gs://chunkedgraph/minnie65_0/edges",
  COMPONENTS= "gs://chunkedgraph/minnie65_0/components",
  WATERSHED= "gs://microns-seunglab/minnie65/ws_minnie65_0"
)
gc = GraphConfig(
  CHUNK_SIZE= [256, 256, 512]
)
cg = ChunkedGraph(graph_id="akhilesh-minnie65-1")

In [2]:
cg.meta.graph_config

GraphConfig(ID=None, ID_PREFIX=None, CHUNK_SIZE=[256, 256, 512], FANOUT=2, LAYER_ID_BITS=8, SPATIAL_BITS=10, OVERWRITE=False, ROOT_LOCK_EXPIRY=datetime.timedelta(seconds=180))

In [14]:
edges = cg.read_chunk_edges([cg.get_chunk_id(layer=2,x=50,y=100,z=0)])
# edges["cross"].get_pairs()

array([[75582903194484746, 75582834475009094],
       [75582903194484755, 75582834475009193],
       [75582903194484757, 75582834475009060],
       [75582903194484766, 75582834475009207],
       [75582903194484774, 75582834475009300],
       [75582903194484777, 75582834475008913],
       [75582903194484798, 75582834475009027],
       [75582903194484812, 75582834475009168],
       [75582903194484819, 75582834475009018],
       [75582903194484829, 75582834475009044],
       [75582903194484834, 75582834475009136],
       [75582903194484834, 75653271938662401],
       [75582903194484849, 75582834475009105],
       [75582903194484873, 75582834475009191],
       [75582903194484877, 75653271938662605],
       [75582903194484912, 75582834475009316],
       [75582903194484963, 75582834475009179],
       [75582903194485062, 75653271938663178],
       [75582903194485077, 75512534450307285],
       [75582903194485109, 75512534450307419],
       [75582903194485150, 75653271938663312],
       [75582

In [5]:
# from collections import defaultdict
# from pychunkedgraph.graph.utils.generic import get_bounding_box
# edge=np.array([75582903194484746, 75582834475009094])
# l2id_agg_d = cg.get_subgraph(
#     agglomeration_ids=np.unique(cg.get_roots(edge.ravel())),
#     bbox=get_bounding_box(None, None),
#     bbox_is_coordinate=True,
#     timestamp=None,
# )
# l2id_agg_d[146725222521765890]

In [4]:
print(cg.get_chunk_layer(291635563662934656))
print(cg.get_children(291635563662934656))

4
[147640497232412674]


In [3]:
# node = cg.client.read_node(147640497232412674)
node = cg.client.read_node(147640428512935937)
node

{_Attribute(key=b'children', family_id='0', serializer=<pychunkedgraph.graph.utils.serializers.NumPyArray object at 0x7efdcb8dcbd0>): [<Cell value=array([75582834475008019, 75582834475008913, 75582834475008902,
         75582834475008889, 75582834475008851, 75582834475008828,
         75582834475008821, 75582834475008814, 75582834475008783,
         75582834475008760, 75582834475008753, 75582834475008725,
         75582834475008723, 75582834475008709, 75582834475009300,
         75582834475008675, 75582834475008669, 75582834475008663,
         75582834475008926, 75582834475008940, 75582834475008941,
         75582834475008951, 75582834475009207, 75582834475009193,
         75582834475009191, 75582834475009168, 75582834475009123,
         75582834475009105, 75582834475009094, 75582834475009060,
         75582834475008659, 75582834475009041, 75582834475009027,
         75582834475009026, 75582834475008998, 75582834475008993,
         75582834475008989, 75582834475008977, 7558283447500897

In [10]:
print(cg.get_parent(75582903194484812))
print(cg.get_parent(75582834475009168))

147640497232412674
147640428512935937


In [6]:
print(cg.get_roots([75582903194484812, 75582834475009168], stop_layer=2))

[147640497232412674 147640428512935937]


In [6]:
print(cg.get_parent(147640497232412674))
print(cg.get_chunk_layer(147640497232412674))
print(cg.get_cross_chunk_edges(147640497232412674))
print(cg.get_atomic_cross_edges([147640497232412674]))

291635563662934656
2
min_layer 4
{4: array([[147640497232412674, 291634464151307295]], dtype=uint64)}
{147640497232412674: {4: array([[75582903194484812, 75582834475009168]], dtype=uint64)}}


In [2]:
print(cg.get_parent(506866064312035921))
print(cg.get_children(506866064312035921))
print(cg.get_chunk_layer(506866064312035921))
print(cg.get_cross_chunk_edges(506866064312035921))

576742227280767262
[435828817064694903 434702917157630643 434702917157524103]
7
nani {_Attribute(key=b'atomic_cross_edges_7', family_id='3', serializer=<pychunkedgraph.graph.utils.serializers.NumPyArray object at 0x7faa7b6eb4d0>): [<Cell value=array([[75441890828222467, 75441822108746685],
       [75441890828222467, 75441822108746676],
       [75441890828222674, 75441822108746874],
       [75441890828222556, 75441822108746723],
       [75441890828222530, 75441822108747024],
       [75441890828222515, 75441822108747016],
       [75441890828222512, 75441822108746748],
       [75441890828222512, 75441822108746678],
       [75441890828222504, 75441822108746748],
       [75441890828222492, 75441822108746748],
       [75441890828222492, 75441822108746759],
       [75441890828222488, 75441822108746782],
       [75441890828222472, 75441822108746800],
       [75441890828222471, 75441822108746800],
       [75441890828222471, 75441822108746771],
       [75441890828222570, 75441822108746685]], dty

In [3]:
cg.get_children(576742227280767262)

array([506795695567722869, 506866064312035921], dtype=uint64)

In [9]:
parent = cg.get_parent(75582903194484812)
while parent:
    print(parent, cg.get_chunk_layer(parent))
    parent = cg.get_parent(parent)

147640497232412674 2
291635563662934656 4
363718446468361184 5
435828817064694903 6
506866064312035921 7
576742227280767262 8
864691138338302132 12


In [10]:
parent = cg.get_parent(75582834475009168)
while parent:
    print(parent, cg.get_chunk_layer(parent))
    parent = cg.get_parent(parent)

147640428512935937 2
219704688340107265 3
291634464151307295 4
363718446468361184 5
435828817064694903 6
506866064312035921 7
576742227280767262 8
864691138338302132 12
