In [1]:
import numpy as np
from pychunkedgraph.graph import ChunkedGraph, ChunkedGraphMeta
from pychunkedgraph.graph.meta import ChunkedGraphMeta, GraphConfig, DataSource

ds = DataSource(
  EDGES= "gs://chunkedgraph/minnie65_0/edges",
  COMPONENTS= "gs://chunkedgraph/minnie65_0/components",
  WATERSHED= "gs://microns-seunglab/minnie65/ws_minnie65_0"
)
gc = GraphConfig(
  CHUNK_SIZE= [256, 256, 512]
)
cg = ChunkedGraph(graph_id="akhilesh-minnie65-1")

In [2]:
cg.meta.graph_config

GraphConfig(ID=None, ID_PREFIX=None, CHUNK_SIZE=[256, 256, 512], FANOUT=2, LAYER_ID_BITS=8, SPATIAL_BITS=10, OVERWRITE=False, ROOT_LOCK_EXPIRY=datetime.timedelta(seconds=180))

In [14]:
edges = cg.read_chunk_edges([cg.get_chunk_id(layer=2,x=50,y=100,z=0)])
# edges["cross"].get_pairs()

array([[75582903194484746, 75582834475009094],
       [75582903194484755, 75582834475009193],
       [75582903194484757, 75582834475009060],
       [75582903194484766, 75582834475009207],
       [75582903194484774, 75582834475009300],
       [75582903194484777, 75582834475008913],
       [75582903194484798, 75582834475009027],
       [75582903194484812, 75582834475009168],
       [75582903194484819, 75582834475009018],
       [75582903194484829, 75582834475009044],
       [75582903194484834, 75582834475009136],
       [75582903194484834, 75653271938662401],
       [75582903194484849, 75582834475009105],
       [75582903194484873, 75582834475009191],
       [75582903194484877, 75653271938662605],
       [75582903194484912, 75582834475009316],
       [75582903194484963, 75582834475009179],
       [75582903194485062, 75653271938663178],
       [75582903194485077, 75512534450307285],
       [75582903194485109, 75512534450307419],
       [75582903194485150, 75653271938663312],
       [75582

In [5]:
# from collections import defaultdict
# from pychunkedgraph.graph.utils.generic import get_bounding_box
# edge=np.array([75582903194484746, 75582834475009094])
# l2id_agg_d = cg.get_subgraph(
#     agglomeration_ids=np.unique(cg.get_roots(edge.ravel())),
#     bbox=get_bounding_box(None, None),
#     bbox_is_coordinate=True,
#     timestamp=None,
# )
# l2id_agg_d[146725222521765890]

In [4]:
cg.get_parent(147570128488235009)

219564225729658884

In [7]:
node = cg.client.read_node(147640497232412674)
node

{_Attribute(key=b'children', family_id='0', serializer=<pychunkedgraph.graph.utils.serializers.NumPyArray object at 0x7fb294f53bd0>): [<Cell value=array([75582903194484812], dtype=uint64) timestamp=2019-11-02 03:59:56.223000+00:00>],
 _Attribute(key=b'parents', family_id='0', serializer=<pychunkedgraph.graph.utils.serializers.NumPyValue object at 0x7fb294f53fd0>): [<Cell value=291635563662934656 timestamp=2019-11-02 18:15:35.986000+00:00>],
 _Attribute(key=b'atomic_cross_edges_4', family_id='3', serializer=<pychunkedgraph.graph.utils.serializers.NumPyArray object at 0x7fb294f53410>): [<Cell value=array([[75582903194484812, 75582834475009168]], dtype=uint64) timestamp=2019-11-02 03:59:56.223000+00:00>]}

In [30]:
print(cg.get_parent(75582903194484812))
print(cg.get_parent(75582834475009168))

147640497232412674
147640428512935937


In [33]:
print(cg.get_roots([75582903194484812, 75582834475009168], stop_layer=4))

[291635563662934656 291634464151307295]


In [11]:
print(cg.get_parent(291634464151307295))
print(cg.get_chunk_layer(291634464151307295))
print(cg.get_cross_chunk_edges(291634464151307295))

363718446468361184
4
[[291634464151307295 291635563662934656]
 [291634464151307295 291635563662936192]]


In [2]:
print(cg.get_parent(506866064312035921))
print(cg.get_children(506866064312035921))
print(cg.get_chunk_layer(506866064312035921))
print(cg.get_cross_chunk_edges(506866064312035921))

576742227280767262
[435828817064694903 434702917157630643 434702917157524103]
7
[[506866064312035921 506795695567722869]]


In [3]:
cg.get_children(576742227280767262)

array([506795695567722869, 506866064312035921], dtype=uint64)

In [9]:
parent = cg.get_parent(75582903194484812)
while parent:
    print(parent, cg.get_chunk_layer(parent))
    parent = cg.get_parent(parent)

147640497232412674 2
291635563662934656 4
363718446468361184 5
435828817064694903 6
506866064312035921 7
576742227280767262 8
864691138338302132 12


In [10]:
parent = cg.get_parent(75582834475009168)
while parent:
    print(parent, cg.get_chunk_layer(parent))
    parent = cg.get_parent(parent)

147640428512935937 2
219704688340107265 3
291634464151307295 4
363718446468361184 5
435828817064694903 6
506866064312035921 7
576742227280767262 8
864691138338302132 12
